github: [DevKilioZOfficiel]
custom: ['https://www.paypal.me/kilioz', 'https://dev-time.eu', 'https://razicord.com', 'https://discord.razicord.com', 'https://twitter.com/RazicordCom', 'https://twitter.com/DevTimeEU']
